[features]
seeds = false
skip-lint = false

[programs.localnet]
instructions = "6nBHnnQ97TBqDaZ7wDFqWkYANT25TKgj218FkTMkv3Ay"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"

[toolchain]
anchor_version = "0.29.0"